spring:
  application:
    name: courierpay
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5432}/${SPRING_DATASOURCE_DATABASE:courierpay}
    username: ${SPRING_DATASOURCE_USERNAME:courierpay}
    password: ${SPRING_DATASOURCE_PASSWORD:courierpay}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: courierpay-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.alihasanov.courierpay.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      missing-topics-fatal: false

server:
  port: ${PORT:8080}

app:
  security:
    jwt-secret: ${JWT_SECRET:VGhlIGhheSBmYWN0b3J5IHJlYWxpemVkIHRoYXQgaXQgd2FudGVkIHRvIGJlIGEgY2F0LCBhbmQgZ3JldyB0ZW50YWNsZXMgb2Ygd2lzZG9tIGluIG9yZGVyIHRvIG92ZXJ0aHJvdyB0aGUgc2VuYXRlLg==}
    jwt-expiration-minutes: ${JWT_EXPIRATION_MINUTES:120}
    refresh-token-expiration-days: ${REFRESH_TOKEN_EXPIRATION_DAYS:7}
  kafka:
    enabled: ${KAFKA_ENABLED:false}
    topics:
      earning-created: ${EARNING_CREATED_TOPIC:earning.created}
      payout-requested: ${PAYOUT_REQUESTED_TOPIC:payout.requested}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
